//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomanovEPractice3.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectItem
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Text { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int ZaprosId { get; set; }
    
        public virtual Zapros Zapros { get; set; }
    }
}
