//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomanovEPractice3.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workers()
        {
            this.WorkerBe = new HashSet<WorkerBe>();
            this.WorkersExpenses = new HashSet<WorkersExpenses>();
        }
    
        public int Id_Worker { get; set; }
        public string FIO { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.TimeSpan TimeOfBirth { get; set; }
        public decimal Salary { get; set; }
        public int PositionId { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkerBe> WorkerBe { get; set; }
        public virtual WorkersPosition WorkersPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkersExpenses> WorkersExpenses { get; set; }
    }
}
